name: FloorUI
description: "Inventory-based GUI library, made for beginners"
version: "0.1.0.DEV"
main: com.boyninja1555.floorui.FloorUI
api-version: "1.21"
folia-supported: true
authors: [ boyninja1555 ]